apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/SEU-PROJETO-ID/worker:latest
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/chave-projeto.json"
        volumeMounts:
        - name: credenciais
          mountPath: /app/chave-projeto.json
          subPath: chave-projeto.json
      volumes:
      - name: credenciais
        secret:
          secretName: firestore-key
