apiVersion: v1
kind: Service
metadata:
  name: critical
spec:
  clusterIP: None  # Headless service!
  selector:
    app: critical
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: critical
  labels:
    app: critical
spec:
  containers:
  - name: critical
    image: victorsusko/critical_server:latest
    env:
    - name: POD_NAME
      value: critical.server