apiVersion: v1
kind: Service
metadata:
  name: critical
spec:
  clusterIP: None  # Headless service para DNS interno
  selector:
    app: critical
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: critical
  labels:
    app: critical
spec:
  containers:
  - name: critical
    image: southamerica-east1-docker.pkg.dev/tp2-sd-467114/repositorio-tp2/critical_server:web
    env:
    - name: POD_NAME
      value: critical.server
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: critical-lb
spec:
  type: LoadBalancer
  selector:
    app: critical
  ports:
    - port: 80       # Porta externa que será acessada via navegador
      targetPort: 8080  # Porta onde sua aplicação escuta no container
