apiVersion: v1
kind: Service
metadata:
  name: server-lb
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
spec:
  serviceName: "server"
  replicas: 5
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: southamerica-east1-docker.pkg.dev/tp2-sd-467114/repositorio-tp2/server:web
        ports:
        - containerPort: 8080
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PEERS
          value: "server-0.server,server-1.server,server-2.server,server-3.server,server-4.server"