kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
      - containerPort: 30081
        hostPort: 30081
      - containerPort: 30082
        hostPort: 30082
      - containerPort: 30083
        hostPort: 30083
      - containerPort: 30084
        hostPort: 30084
      - containerPort: 30085
        hostPort: 30085
      - containerPort: 30091
        hostPort: 30091
      - containerPort: 30092
        hostPort: 30092
      - containerPort: 30093
        hostPort: 30093
