apiVersion: v1
kind: Service
metadata:
  name: critical
spec:
  clusterIP: None  # Headless service para DNS interno
  selector:
    app: critical
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: critical
  labels:
    app: critical
spec:
  containers:
  - name: critical
    image: victorsusko/critical_server:web
    env:
    - name: POD_NAME
      value: critical.server
    ports:
    - containerPort: 8080
---
# Novo serviço NodePort para acesso externo
apiVersion: v1
kind: Service
metadata:
  name: critical-nodeport
spec:
  type: NodePort
  selector:
    app: critical
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30086
