apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 5
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: cristianomafuz/client:latest
        env:
        - name: SERVER_HOST
          value: server-service
