apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  clusterIP: None  # Headless service!
  selector:
    app: server
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
spec:
  serviceName: "server"
  replicas: 5
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: cristianomafuz/server:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PEERS
          value: "server-0.server,server-1.server,server-2.server"
